name: Repo_Sync_with_Key
on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 0-15 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Init Build Dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E rm -rf /etc/apt/sources.list.d
        sudo -E apt-get update -y && apt-get install -y build-essential git git-core curl wget && apt-get clean -y
        git config --global user.name 'GitHub Actions' && git config --global user.email 'noreply@github.com'
    - name: Prepare
      run: |
        mkdir -p ~/.ssh
        echo -e "${{ secrets.KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan gitee.com > ~/.ssh/known_hosts
    - name: Clone dev
      run: |
        git clone -b dev git@jd_base_gitee:supermanito/jd_base.git dev
    - name: Push dev
      uses: ad-m/github-push-action@master
      with:
        directory: dev
        github_token: ${{ secrets.TOKEN }}
        branch: dev
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ secrets.TOKEN }}
        retain_days: 1
        keep_minimum_runs: 2
