name: Repo_Sync
on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Init Build Dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E rm -rf /etc/apt/sources.list.d
        sudo -E apt-get update -y && apt-get install -y build-essential git git-core curl wget && apt-get clean -y
        git config --global user.name 'GitHub Actions' && git config --global user.email 'noreply@github.com'
    - name: Clone QingLong
      run: |
        git clone -b master https://github.com/whyour/qinglong.git qinglong
    - name: Push QingLong
      uses: ad-m/github-push-action@master
      with:
        directory: qinglong
        github_token: ${{ secrets.TOKEN }}
        branch: qinglong
    - name: Clone sillyGirl
      run: |
        git clone -b main https://github.com/cdle/sillyGirl.git sillygirl
    - name: Push sillyGirl
      uses: ad-m/github-push-action@master
      with:
        directory: sillygirl
        github_token: ${{ secrets.TOKEN }}
        branch: sillygirl
    - name: Clone KingRan
      run: |
        git clone -b main https://github.com/KingRan/KR.git scripts3
    - name: Push Scripts3
      uses: ad-m/github-push-action@master
      with:
        directory: scripts3
        github_token: ${{ secrets.TOKEN }}
        branch: scripts3
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ secrets.TOKEN }}
        retain_days: 1
        keep_minimum_runs: 2
